FROM nginx:stable-alpine

RUN delgroup dialout

RUN addgroup -g 1000 --system laravel
RUN adduser -G laravel --system -D -s /bin/sh -u 1000 laravel
RUN sed -i "s/user  nginx/user laravel/g" /etc/nginx/nginx.conf

ADD ./nginx/default.conf /etc/nginx/conf.d/
ADD ./nginx/nginx.conf /etc/nginx

COPY --from=beekay6/laravel:0.2 /var/www/html/ /var/www/html/
RUN chown -R laravel: /var/www/html